### ISSUE TITLE
An Unexpected Error Was Encountered

### ISSUE THREAD

**Issue by linnilbobo** [Shirakumo/reader#1]
Unfortunately something happened that we did not anticipate. Hopefully the problem will not persist.

Unfortunately, no detailed reason for this problem is available.

---

* 2020-08-18 09:19:15 [WARN ] <RADIANCE>: NIL fell through ECASE expression.
Wanted one of (:PLAIN :HTML :MARKDOWN :MARKLESS).
   [Condition of type SB-KERNEL:CASE-FAILURE]

#<ENVIRONMENT {10082384A3}>
   [Environment of thread #<THREAD "localhost:8080" RUNNING {1001ECFED3}>]

Available restarts:
 0: [STUB] Create a stub file instead.
 1: [BAIL] Bail out, potentially leaving no cache file behind (dangerous).
 2: [CONTINUE] Skip triggering 'READER::READER-CACHE.
 3: [ABORT] Abort triggering READER::ARTICLE-UPDATED.
 4: [ABORT-HANDLING] Abort the current handler and continue dispatching.
 5: [SET-DATA] Set the response data.
 6: [ABORT] abort thread (#<THREAD "localhost:8080" RUNNING {1001ECFED3}>)

Backtrace:
 5: ((:METHOD VERBOSE:LOG (T T CONDITION)) WARN RADIANCE NIL fell through ECASE expression. Wanted one of (:PLAIN :HTML :MARKDOWN :MARKLESS).)
 6: (HANDLE-CONDITION NIL fell through ECASE expression. Wanted one of (:PLAIN :HTML :MARKDOWN :MARKLESS).)
 7: (SB-KERNEL::%SIGNAL NIL fell through ECASE expression. Wanted one of (:PLAIN :HTML :MARKDOWN :MARKLESS).)
 8: (ERROR CASE-FAILURE NAME ECASE DATUM NIL EXPECTED-TYPE (MEMBER PLAIN HTML MARKDOWN MARKLESS) POSSIBILITIES (PLAIN HTML MARKDOWN MARKLESS))
 9: (SB-KERNEL:INTERNAL-ERROR #.(SB-SYS:INT-SAP #X7FA7651752C0) #<unused argument>)
 10: ("foreign function: call_into_lisp")
 11: ("foreign function: funcall2")
 12: ("foreign function: interrupt_internal_error")
 13: ("foreign function: handle_trap")
 14: ("foreign function: #x559A1C449011")
 15: (READER::PARSE aaa)
 16: (READER::ARTICLE-CONTENT #<DATA-MODEL ARTICLES:2>)
 17: (READER::ARTICLE-DESCRIPTION #<DATA-MODEL ARTICLES:2>)
 18: ((LAMBDA (CLIP::NODE CLIP::VALUE) :IN "/home/lin/quicklisp/dists/shirakumo/software/clip-2020.07.10_17-16-22-GMT/attr-processors.lisp") #<ELEMENT meta {100821AF73}> (attr :content (reader::article-description article)))
 19: (PROCESS-ATTRIBUTES #<ELEMENT meta {100821AF73}>)
 20: (PROCESS-TAG meta #<ELEMENT meta {100821AF73}>)
 21: (PROCESS-NODE #<ELEMENT meta {100821AF73}>)
 22: (PROCESS-CHILDREN #<ELEMENT head {1008214D83}>)
 23: (PROCESS-NODE #<ELEMENT head {1008214D83}>)
 24: (PROCESS-CHILDREN #<ELEMENT html {10082148E3}>)
 25: (PROCESS-NODE #<ELEMENT html {10082148E3}>)
 26: (PROCESS-CHILDREN #<ROOT {1008214193}>)
 27: (PROCESS-NODE #<ROOT {1008214193}>)
 28: (PROCESS #<ROOT {1008214193}> ARTICLE #<DATA-MODEL ARTICLES:2> NEXT NIL PREV #<DATA-MODEL ARTICLES:1> LINKS NIL TITLE my blogs DESCRIPTION NIL)
 29: (R-CLIP:PROCESS T ARTICLE #<DATA-MODEL ARTICLES:2> NEXT NIL PREV #<DATA-MODEL ARTICLES:1> LINKS NIL TITLE my blogs DESCRIPTION NIL)
 30: (READER::CALL-WITH-TEMPLATE-TO-CACHE ~/.cache/radiance/default/reader/ARTICLE/2.html article.ctml #<CLOSURE (LAMBDA NIL :IN READER::RECACHE-ARTICLE) {10081FCA7B}>)
 31: (READER::RECACHE-ARTICLE #<DATA-MODEL ARTICLES:2> T)
 32: ((LAMBDA (READER::ARTICLE) :IN "/home/lin/quicklisp/dists/shirakumo/software/reader-2020.07.10_17-16-26-GMT/cache.lisp") #<DATA-MODEL ARTICLES:2>)
 33: ((:METHOD MODULARIZE-HOOKS::RUN-TRIGGERS (HOOK T)) #<HOOK ARTICLE-UPDATED> (#<DATA-MODEL ARTICLES:2>))
 34: ((FLET "DISPATCHER16" :IN "/home/lin/quicklisp/dists/shirakumo/software/reader-2020.07.10_17-16-26-GMT/reader.lisp"))
 35: (DISPATCH #@"reader:8080/write/")
 36: (EXECUTE-REQUEST #<unavailable argument> #<unavailable argument>)
 37: (REQUEST #<unavailable argument> REPRESENTATION #<unavailable argument> HTTP-METHOD #<unavailable argument> BODY-STREAM #<unavailable argument> HEADERS #<unavailable argument> POST #<unavailable argument> GET #<unavailable argument> COOKIES #<unavailable argument> REMOTE #<unavailable argument> RESPONSE #<unavailable argument>)
 38: ((:METHOD HUNCHENTOOT:ACCEPTOR-DISPATCH-REQUEST (I-HUNCHENTOOT::RADIANCE-ACCEPTOR T)) #<unused argument> #<REQUEST {10081CD3C3}>)
 39: ((:METHOD HUNCHENTOOT:HANDLE-REQUEST (HUNCHENTOOT:ACCEPTOR HUNCHENTOOT:REQUEST)) #<RADIANCE-ACCEPTOR (host 0.0.0.0, port 8080)> #<REQUEST {10081CD3C3}>)
 40: ((:METHOD HUNCHENTOOT:PROCESS-REQUEST (T)) #<REQUEST {10081CD3C3}>)
 41: (HUNCHENTOOT::DO-WITH-ACCEPTOR-REQUEST-COUNT-INCREMENTED #<RADIANCE-ACCEPTOR (host 0.0.0.0, port 8080)> #<CLOSURE (LAMBDA NIL :IN HUNCHENTOOT:PROCESS-CONNECTION) {10081CD32B}>)
 42: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION (HUNCHENTOOT:ACCEPTOR T)) #<RADIANCE-ACCEPTOR (host 0.0.0.0, port 8080)> #<STREAM-USOCKET {1001D7FCA3}>)
 43: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND (HUNCHENTOOT:ACCEPTOR T)) #<RADIANCE-ACCEPTOR (host 0.0.0.0, port 8080)> #<STREAM-USOCKET {1001D7FCA3}>)
 44: ((FLET HUNCHENTOOT::PROCESS-CONNECTION% :IN HUNCHENTOOT::HANDLE-INCOMING-CONNECTION%) #<RADIANCE-ACCEPTOR (host 0.0.0.0, port 8080)> #<STREAM-USOCKET {1001D7FCA3}>)
 45: ((FLET I-HUNCHENTOOT::THUNK :IN HUNCHENTOOT:START-THREAD))
 46: ((LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
 47: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 48: ((FLET "WITHOUT-INTERRUPTS-BODY-9" :IN SB-THREAD::RUN))
 49: (SB-THREAD::RUN #<THREAD "localhost:8080" RUNNING {1001ECFED3}> NIL #<CLOSURE (LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1001ECFE7B}> NIL)
 50: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 51: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::START-THREAD) {7FA765176E4B}> #<MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "localhost:8080" RUNNING {1001ECFED3}>> T NIL)
 52: ((FLET SB-THREAD::START-ROUTINE :IN SB-THREAD::START-THREAD))
 53: ("foreign function: call_into_lisp")
 54: ("foreign function: new_thread_trampoline")
2020-08-18 09:19:15 [WARN ] <RADIANCE>: Handling stray condition: NIL fell through ECASE expression.
                          Wanted one of (:PLAIN :HTML :MARKDOWN :MARKLESS).

**Comment by Shinmera** [comment]
What did you do to get this error? Is this a fresh install? An upgrade?

**Comment by linnilbobo** [comment]
hi, thanks for answer
i want to build a blog by Radiance and reader 
```common lisp
(ql-dist:install-dist "http://dist.tymoon.eu/shirakumo.txt")
(ql:quickload :radiance)
(radiance:startup)
;Implementation
;SBCL 2.0.7
;Radiance 2.1.2
;Quicklisp 2020-07-15
(in-package :rad-user)
(ql:quickload :reader)
(setf (radiance:mconfig :reader :title) "The Blog")
;log in
;Register an Account, name linnil
(user:grant "linnil" '(reader write))
;http://localhost:8080/!/reader/write/
;i type title:abc tag:a text:hello
;i click on the save
;then turn to that error page
;http://localhost:8080/!/reader/write/#
;i shows Internal Server Error

;please help me, thanks
```

**Comment by Shinmera** [comment]
Try:
`(setf (radiance:mconfig :reader :markup) :markdown)`

It should do that on its own when you install it, so I'm a bit confused about how the error is possible in the first place.

**Comment by linnilbobo** [comment]
well, after `(setf (radiance:mconfig :reader :markup) :markdown)` it works 
thanks a lot, and i can see the articles on http://localhost:8080/!/reader/
http://localhost:8080/!/reader/article/0 can see the article
http://localhost:8080/!/reader/write/0 can save change or delete it
Thanks for your assistance;)
